repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
-   repo: https://github.com/biomejs/pre-commit
    rev: v2.0.0-beta.5
    hooks:
    -   id: biome-check
        additional_dependencies: ["@biomejs/biome@2.0.0"]
        files: ^/frontend/src.*\.(js|ts|tsx)$
