name: Style Checks

on: ["push", "pull_request"]

jobs:
  style:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Deps
        run: |
          pip install flake8 pep8-naming
      - name: Style Checks
        run: |
          flake8 .
