name: Playwright Tests

on: ["push", "pull_request"]

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Setup Playwright
        run: |
          cd playwright
          npx playwright install --with-deps
      - name: Run Playwright Tests
        run: |
          cd playwright
          npx playwright test
